name: Build Android

on:
  push:
    branches: 
      - '**'
    paths:
      - 'Android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create keystore.properties
        run: |
          cat <<EOF > keystore.properties
          intelity_jfrog_user=${{ secrets.USER }}
          intelity_jfrog_password=${{ secrets.PASSWORD }}
          EOF

      - name: Build Compose app
        run: ./gradlew assembleDebug
